//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Innotm.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransID { get; set; }
        public int UserId { get; set; }
        public int RefId { get; set; }
        public int TransType { get; set; }
        public decimal InitialAmount { get; set; }
        public decimal AmountTransfer { get; set; }
        public System.DateTime Date { get; set; }
        public int Status { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
